---

- hosts: all
  become: true
  tasks:
  # - name: update repo index
  #   apt:
  #     update_cache: yes
  # - name: install apache2 package and add php support for apache
  #   apt:
  #     name: 
  #       - apache2
  #       - libapache2-mod-php
  #     state: latest
  #     update_cache: yes
  - name: install apache and php
    package:
      name: 
        - "{{ apache }}" 
        - "{{ php }}"
      state: latest
      update_cache: yes
  